version: '3'

services:
  web:
    build: .
    ports:
      - 80:80
    volumes:
      - .:/var/www/html:cached
    depends_on:
      - db
      - redis

  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: magento
      MYSQL_DATABASE: magento
      MYSQL_USER: magento
      MYSQL_PASSWORD: magento

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8080:80
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: magento
      MYSQL_DATABASE: magento
      MYSQL_USER: magento
      MYSQL_PASSWORD: magento
    links:
      - db
    volumes:
     - /sessions

  redis:
    image: redis:latest
    ports:
      - 6379:6379

volumes:
  db_data:
